/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.empleado;

/**
 *
 * @author zuzul
 */
public class EmpleadoFrame extends javax.swing.JFrame {

    /**
     * Creates new form EmpleadoFrame
     */
    public EmpleadoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcodigoempleado = new javax.swing.JTextField();
        txtnombreempleado = new javax.swing.JTextField();
        txthorasempleado = new javax.swing.JTextField();
        txtcvalorhoraempleado = new javax.swing.JTextField();
        txtporcentajeretencionempleado = new javax.swing.JTextField();
        BtnsalarioBrutoempleado = new javax.swing.JButton();
        BtnsalarioNetoempleado = new javax.swing.JButton();
        BtnBorrarempleado = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtbrutoempleado = new javax.swing.JTextField();
        txtNetoempleado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Datos del Empleado");

        jLabel2.setText("Codigo");

        jLabel3.setText("Nombre");

        jLabel4.setText("Nro de horas trabajadas");

        jLabel5.setText("Valor Hora");

        jLabel6.setText("Porcentaje de Retencion");

        txtcvalorhoraempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcvalorhoraempleadoActionPerformed(evt);
            }
        });

        txtporcentajeretencionempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtporcentajeretencionempleadoActionPerformed(evt);
            }
        });

        BtnsalarioBrutoempleado.setText("Calcular salario Bruto");
        BtnsalarioBrutoempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnsalarioBrutoempleadoActionPerformed(evt);
            }
        });

        BtnsalarioNetoempleado.setText("Calcular salario  Neto");
        BtnsalarioNetoempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnsalarioNetoempleadoActionPerformed(evt);
            }
        });

        BtnBorrarempleado.setText("Borrar");
        BtnBorrarempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarempleadoActionPerformed(evt);
            }
        });

        jLabel7.setText("Salario Bruto");

        jLabel8.setText("Salario Neto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnsalarioBrutoempleado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(126, 126, 126)
                                    .addComponent(BtnsalarioNetoempleado)
                                    .addGap(18, 18, 18)
                                    .addComponent(BtnBorrarempleado))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(95, 95, 95)
                                        .addComponent(txtNetoempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(92, 92, 92)
                                        .addComponent(txtbrutoempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(121, 121, 121)
                                        .addComponent(txtcodigoempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtnombreempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txthorasempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(103, 103, 103)
                                            .addComponent(txtcvalorhoraempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(31, 31, 31)
                                .addComponent(txtporcentajeretencionempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(126, 126, 126)))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcodigoempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnombreempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txthorasempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtporcentajeretencionempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(txtbrutoempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtNetoempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnsalarioBrutoempleado)
                            .addComponent(BtnsalarioNetoempleado)
                            .addComponent(BtnBorrarempleado)))
                    .addComponent(txtcvalorhoraempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcvalorhoraempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcvalorhoraempleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcvalorhoraempleadoActionPerformed

    private void txtporcentajeretencionempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtporcentajeretencionempleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtporcentajeretencionempleadoActionPerformed

    private void BtnsalarioBrutoempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnsalarioBrutoempleadoActionPerformed
        // TODO add your handling code here:
        
        String codigo, nombre;
        int horasTrabajadas;
        double valorHora, porcentajeRetencion;
        double salarioBruto;

        codigo = txtcodigoempleado.getText();
        nombre = txtnombreempleado.getText();
        horasTrabajadas = Integer.parseInt(txthorasempleado.getText());
        valorHora = Double.parseDouble(txtcvalorhoraempleado.getText());
        porcentajeRetencion = Double.parseDouble(txtporcentajeretencionempleado.getText());
        Empleado empleadovariante = new Empleado(codigo, nombre, horasTrabajadas, valorHora, porcentajeRetencion);
        salarioBruto = empleadovariante.calcularSalarioBruto();
        txtbrutoempleado.setText(String.valueOf(salarioBruto));
    }//GEN-LAST:event_BtnsalarioBrutoempleadoActionPerformed

    private void BtnsalarioNetoempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnsalarioNetoempleadoActionPerformed
        // TODO add your handling code here:
        String codigo, nombre;
        int horasTrabajadas;
        double valorHora, porcentajeRetencion;
        double salarioNeto;

        codigo = txtcodigoempleado.getText();
        nombre = txtnombreempleado.getText();
        horasTrabajadas = Integer.parseInt(txthorasempleado.getText());
        valorHora = Double.parseDouble(txtcvalorhoraempleado.getText());
        porcentajeRetencion = Double.parseDouble(txtporcentajeretencionempleado.getText());
        Empleado empleadovariante = new Empleado(codigo, nombre, horasTrabajadas, valorHora, porcentajeRetencion);
        salarioNeto = empleadovariante.calcularSalarioNeto();
        txtNetoempleado.setText(String.valueOf(salarioNeto));
    }//GEN-LAST:event_BtnsalarioNetoempleadoActionPerformed

    private void BtnBorrarempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarempleadoActionPerformed
        // TODO add your handling code here:
        txtcodigoempleado.setText("");
        txtnombreempleado.setText("");
        txthorasempleado.setText("");
        txtcvalorhoraempleado.setText("");
        txtporcentajeretencionempleado.setText("");
        txtbrutoempleado.setText("");
        txtNetoempleado.setText("");
    }//GEN-LAST:event_BtnBorrarempleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpleadoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpleadoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpleadoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpleadoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpleadoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBorrarempleado;
    private javax.swing.JButton BtnsalarioBrutoempleado;
    private javax.swing.JButton BtnsalarioNetoempleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtNetoempleado;
    private javax.swing.JTextField txtbrutoempleado;
    private javax.swing.JTextField txtcodigoempleado;
    private javax.swing.JTextField txtcvalorhoraempleado;
    private javax.swing.JTextField txthorasempleado;
    private javax.swing.JTextField txtnombreempleado;
    private javax.swing.JTextField txtporcentajeretencionempleado;
    // End of variables declaration//GEN-END:variables
}
