/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.encontrarmayor;

/**
 *
 * @author zuzul
 */
public class EncontrarMayorFrame extends javax.swing.JFrame {

    /**
     * Creates new form EncontrarMayorFrame
     */
    public EncontrarMayorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnumeros = new javax.swing.JTextField();
        txtmayorr = new javax.swing.JTextField();
        BtnBorro = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Btnmayor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("¿Que numero es mayor?");

        jLabel2.setText("Ingrese los numeros");

        BtnBorro.setText("Borrar");
        BtnBorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorroActionPerformed(evt);
            }
        });

        jLabel3.setText("El mayor es:");

        Btnmayor.setText("Calcular mayor");
        Btnmayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnmayorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(92, 92, 92)
                                .addComponent(txtnumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(52, 52, 52)
                                .addComponent(Btnmayor)
                                .addGap(49, 49, 49)
                                .addComponent(txtmayorr, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BtnBorro))))
                .addContainerGap(313, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtnumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(txtmayorr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(Btnmayor)))
                .addGap(30, 30, 30)
                .addComponent(BtnBorro)
                .addContainerGap(273, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorroActionPerformed
        txtnumeros.setText("");
        txtmayorr.setText("");
    }//GEN-LAST:event_BtnBorroActionPerformed

    private void BtnmayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnmayorActionPerformed
            try {
        // Leer los números ingresados en el campo de texto
        String numerosText = txtnumeros.getText();
        
        // Separar los números por comas y convertirlos a un arreglo de enteros
        String[] numerosArray = numerosText.split(",");
        int[] numeros = new int[numerosArray.length];
        for (int i = 0; i < numerosArray.length; i++) {
            int numero = Integer.parseInt(numerosArray[i].trim());
            // Verificar si el número es positivo
            if (numero <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese solo números enteros positivos.", "Error de entrada", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            numeros[i] = numero;
        }
        
        // Crear una instancia de EncontrarMayor con el grupo de números
        EncontrarMayor encontrarMayor = new EncontrarMayor(numeros);
        
        // Encontrar el mayor valor y mostrarlo en el campo de texto
        int mayorValor = encontrarMayor.encontrarMayorValor();
        txtmayorr.setText(String.valueOf(mayorValor));
    } catch (NumberFormatException e) {
        // Mostrar mensaje de error si la entrada no es válida
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese números enteros válidos separados por comas.", "Error de entrada", javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (IllegalArgumentException e) {
        // Mostrar mensaje de error si el grupo de números está vacío
        javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Error de entrada", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BtnmayorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EncontrarMayorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EncontrarMayorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EncontrarMayorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EncontrarMayorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EncontrarMayorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBorro;
    private javax.swing.JButton Btnmayor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtmayorr;
    private javax.swing.JTextField txtnumeros;
    // End of variables declaration//GEN-END:variables
}
