/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.operacionnumerica;

/**
 *
 * @author zuzul
 */
public class OperacionNumericaFrame extends javax.swing.JFrame {

    /**
     * Creates new form OperacionNumericaFrame
     */
    public OperacionNumericaFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnumero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Btnraiz = new javax.swing.JButton();
        txtraiz = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Btncalcularcuadrado = new javax.swing.JButton();
        txtcuadrado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Btncalcularcubo = new javax.swing.JButton();
        txtcubo = new javax.swing.JTextField();
        Btncalcularotro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Operacion Numerica");

        jLabel2.setText("Ingrese un numero");

        jLabel3.setText("Su raiz cuadrada es:");

        Btnraiz.setText("Calcular raiz");
        Btnraiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnraizActionPerformed(evt);
            }
        });

        jLabel4.setText("Su cuadrado es: ");

        Btncalcularcuadrado.setText("Calcular cuadrado");
        Btncalcularcuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtncalcularcuadradoActionPerformed(evt);
            }
        });

        jLabel5.setText("Su cubo es: ");

        Btncalcularcubo.setText("Calcular cubo");
        Btncalcularcubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtncalcularcuboActionPerformed(evt);
            }
        });

        Btncalcularotro.setText("Calcular otro numero");
        Btncalcularotro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtncalcularotroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btncalcularotro)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(49, 49, 49)
                        .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Btnraiz)
                                    .addComponent(Btncalcularcuadrado)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(54, 54, 54)
                                .addComponent(Btncalcularcubo)))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtraiz, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(txtcuadrado)
                            .addComponent(txtcubo))))
                .addContainerGap(355, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Btnraiz)
                    .addComponent(txtraiz, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Btncalcularcuadrado)
                    .addComponent(txtcuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Btncalcularcubo)
                    .addComponent(txtcubo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(Btncalcularotro)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtncalcularcuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtncalcularcuadradoActionPerformed

    try {
        int numero = Integer.parseInt(txtnumero.getText());

        if (numero > 0) {
            OperacionNumerica numerica = new OperacionNumerica(numero);
            double cuadrado = numerica.calcularCuadrado();
            txtcuadrado.setText(String.valueOf(cuadrado));
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese un número entero positivo.", "Error de entrada", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese un número entero válido.", "Error de entrada", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BtncalcularcuadradoActionPerformed

    private void BtncalcularotroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtncalcularotroActionPerformed
        // TODO add your handling code here:
        txtnumero.setText("");
        txtraiz.setText("");
        txtcuadrado.setText("");
        txtcubo.setText("");
    }//GEN-LAST:event_BtncalcularotroActionPerformed

    private void BtnraizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnraizActionPerformed
    try {
        int numero = Integer.parseInt(txtnumero.getText());

        if (numero > 0) {
            OperacionNumerica numerica = new OperacionNumerica(numero);
            double raiz = numerica.calcularRaiz();
            txtraiz.setText(String.valueOf(raiz));
        } else {
            // Mostrar mensaje de error si el número no es positivo
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese un número entero positivo.", "Error de entrada", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        // Mostrar mensaje de error si la entrada no es un número válido
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese un número entero válido.", "Error de entrada", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BtnraizActionPerformed

    private void BtncalcularcuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtncalcularcuboActionPerformed
     try {
        int numero = Integer.parseInt(txtnumero.getText());

        if (numero > 0) {
            OperacionNumerica numerica = new OperacionNumerica(numero);
            double cubo = numerica.calcularCubo();
            txtcubo.setText(String.valueOf(cubo));
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese un número entero positivo.", "Error de entrada", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese un número entero válido.", "Error de entrada", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BtncalcularcuboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperacionNumericaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperacionNumericaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperacionNumericaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperacionNumericaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperacionNumericaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btncalcularcuadrado;
    private javax.swing.JButton Btncalcularcubo;
    private javax.swing.JButton Btncalcularotro;
    private javax.swing.JButton Btnraiz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtcuadrado;
    private javax.swing.JTextField txtcubo;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtraiz;
    // End of variables declaration//GEN-END:variables
}
