/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pruebafiguras;

/**
 *
 * @author zuzul
 */
public class ventanaprincipal extends javax.swing.JFrame {

    /**
     * Creates new form ventanaprincipal
     */
    public ventanaprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtcuadradolado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtbaserectangulo = new javax.swing.JTextField();
        txtalturarectangulo = new javax.swing.JTextField();
        Btnarearectangulo = new javax.swing.JButton();
        txtarearectangulo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtperimetrorectangulo = new javax.swing.JTextField();
        Bntborrarrectangulo = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        Btnhipotenusatriangulo = new javax.swing.JButton();
        Btnperimetrotriangulo = new javax.swing.JButton();
        Btnareatriangulo = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtradiocirculo = new javax.swing.JTextField();
        txtareacirculo = new javax.swing.JTextField();
        txtperimetrocirculo = new javax.swing.JTextField();
        Btnareacirculo = new javax.swing.JButton();
        Btnperimetrocirculo = new javax.swing.JButton();
        BtnBorrarCirculo = new javax.swing.JButton();
        Btnperimetrorectangulo = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtbasetriangulo = new javax.swing.JTextField();
        txtalturatriangulo = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtareatriangulo = new javax.swing.JTextField();
        txtperimetrotriangulo = new javax.swing.JTextField();
        txthipotenusatriangulo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtladorombo = new javax.swing.JTextField();
        txtmayorrombo = new javax.swing.JTextField();
        txtmenorrombo = new javax.swing.JTextField();
        Btnarearombo = new javax.swing.JButton();
        Btnperimetrorombo = new javax.swing.JButton();
        Btnborrararombo = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        txtarearombo = new javax.swing.JTextField();
        txtperimetrorombo = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        Btnareatrapecio = new javax.swing.JButton();
        Btnperimetrotrapecio = new javax.swing.JButton();
        txtlado1trapecio = new javax.swing.JTextField();
        txtlado2trapecio = new javax.swing.JTextField();
        txtbasemayortrapecio = new javax.swing.JTextField();
        txtbasemenortrapecio = new javax.swing.JTextField();
        txtalturatrapecio = new javax.swing.JTextField();
        Btnborrartrapecio = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        txtareatrapecio = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtperimetrotrapecio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BtnareaCuadrado = new javax.swing.JButton();
        BtnBorrarCuadrado = new javax.swing.JButton();
        BtnperimetroCuadrado = new javax.swing.JButton();
        txtcuadradoarea = new javax.swing.JTextField();
        txtcuadradoperimetro = new javax.swing.JTextField();
        Btnborrartriangulo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Cuadrado");

        jLabel6.setText("Lado del cuadrado");

        jLabel7.setText("jLabel7");

        jLabel1.setText("Rectangulo");

        jLabel2.setText("Base rectangulo");

        jLabel3.setText("Altura rectangulo");

        jLabel4.setText("El area rectangulo es:");

        Btnarearectangulo.setText("Calcular area rectangulo");
        Btnarearectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnarearectanguloActionPerformed(evt);
            }
        });

        jLabel10.setText("El perimetro es:");

        Bntborrarrectangulo.setText("Borrar valor rectangulo");
        Bntborrarrectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntborrarrectanguloActionPerformed(evt);
            }
        });

        Btnhipotenusatriangulo.setText("Calcular Hipotenusa ");
        Btnhipotenusatriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnhipotenusatrianguloActionPerformed(evt);
            }
        });

        Btnperimetrotriangulo.setText("Calcular perimetro Triangulo ");
        Btnperimetrotriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnperimetrotrianguloActionPerformed(evt);
            }
        });

        Btnareatriangulo.setText("Calcular area Triangulo ");
        Btnareatriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnareatrianguloActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(Btnhipotenusatriangulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Btnperimetrotriangulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Btnareatriangulo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 70, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btnperimetrotriangulo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btnhipotenusatriangulo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btnareatriangulo, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(Btnareatriangulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btnperimetrotriangulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btnhipotenusatriangulo)
                .addContainerGap())
        );

        jLabel11.setText("Circulo");

        jLabel12.setText("radio");

        jLabel13.setText("Area del circulo");

        jLabel14.setText("Perimetro circulo");

        txtperimetrocirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtperimetrocirculoActionPerformed(evt);
            }
        });

        Btnareacirculo.setText("Calcular area circulo");
        Btnareacirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnareacirculoActionPerformed(evt);
            }
        });

        Btnperimetrocirculo.setText("Calcular perimetro circulo");
        Btnperimetrocirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnperimetrocirculoActionPerformed(evt);
            }
        });

        BtnBorrarCirculo.setText("Borrar resultados circulo");
        BtnBorrarCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarCirculoActionPerformed(evt);
            }
        });

        Btnperimetrorectangulo.setText("Calcular perimetro rectangulo");
        Btnperimetrorectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnperimetrorectanguloActionPerformed(evt);
            }
        });

        jLabel15.setText("Triangulo");

        jLabel16.setText("base Triangulo");

        jLabel17.setText("Altura Triangulo ");

        txtbasetriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbasetrianguloActionPerformed(evt);
            }
        });

        jLabel18.setText("Area Triangulo ");

        jLabel19.setText("Perimetro Triangulo");

        jLabel20.setText("La hipotenusa es:");

        jLabel21.setText("Rombo");

        jLabel22.setText("Lado Rombo");

        jLabel23.setText("Diagonal Mayor");

        jLabel24.setText("Diagonal Menor");

        txtladorombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtladoromboActionPerformed(evt);
            }
        });

        Btnarearombo.setText("Calcular area rombo");
        Btnarearombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnarearomboActionPerformed(evt);
            }
        });

        Btnperimetrorombo.setText("Calcular perimetro rombo");
        Btnperimetrorombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnperimetroromboActionPerformed(evt);
            }
        });

        Btnborrararombo.setText("Borrar datos rombo");
        Btnborrararombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnborrararomboActionPerformed(evt);
            }
        });

        jLabel25.setText("El rea rombo es:");

        txtperimetrorombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtperimetroromboActionPerformed(evt);
            }
        });

        jLabel26.setText("Perimetro rombo");

        jLabel27.setText("Trapecio");

        jLabel28.setText("Lado1");

        jLabel29.setText("Lado2 ");

        jLabel30.setText("Base Mayor");

        jLabel31.setText("Base Menor");

        jLabel32.setText("Altura");

        Btnareatrapecio.setText("Calcular area trapecio");
        Btnareatrapecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnareatrapecioActionPerformed(evt);
            }
        });

        Btnperimetrotrapecio.setText("Calcular perimetro trapecio");
        Btnperimetrotrapecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnperimetrotrapecioActionPerformed(evt);
            }
        });

        Btnborrartrapecio.setText("Borrar datos trapecio");
        Btnborrartrapecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnborrartrapecioActionPerformed(evt);
            }
        });

        jLabel33.setText("El area es:");

        jLabel35.setText("El perimetro es:");

        jLabel8.setText("Area del cuadrado");

        jLabel9.setText("Perimetro del cuadrado");

        BtnareaCuadrado.setText("Calcular Area del cuadrado");
        BtnareaCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnareaCuadradoActionPerformed(evt);
            }
        });

        BtnBorrarCuadrado.setText("Borrar valores");
        BtnBorrarCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarCuadradoActionPerformed(evt);
            }
        });

        BtnperimetroCuadrado.setText("Perimetro cuadrado");
        BtnperimetroCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnperimetroCuadradoActionPerformed(evt);
            }
        });

        txtcuadradoarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcuadradoareaActionPerformed(evt);
            }
        });

        txtcuadradoperimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcuadradoperimetroActionPerformed(evt);
            }
        });

        Btnborrartriangulo.setText("Borrar valores Triangulo");
        Btnborrartriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnborrartrianguloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtbaserectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtperimetrorectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtarearectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtalturarectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(Btnborrartriangulo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(93, 93, 93)
                                                .addComponent(jLabel5)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel15)
                                        .addGap(84, 84, 84))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(140, 140, 140)
                                        .addComponent(txtcuadradolado, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addGap(23, 23, 23)
                                                .addComponent(txtalturatriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel16)
                                                    .addGap(34, 34, 34)
                                                    .addComponent(txtbasetriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel18)
                                                    .addGap(31, 31, 31)
                                                    .addComponent(txtareatriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel19)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtperimetrotriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel20)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(txthipotenusatriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(44, 44, 44)
                                                .addComponent(txtcuadradoarea, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtcuadradoperimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(BtnareaCuadrado)
                                            .addComponent(BtnperimetroCuadrado)
                                            .addComponent(BtnBorrarCuadrado))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 103, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Btnperimetrocirculo)
                                    .addComponent(Btnareacirculo)
                                    .addComponent(BtnBorrarCirculo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtperimetrocirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel13)
                                                .addComponent(jLabel12)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtradiocirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtareacirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addComponent(jLabel21)
                                        .addGap(94, 94, 94))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Btnborrararombo)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel25)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtarearombo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel26)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtperimetrorombo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(1, 1, 1)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel23)
                                                        .addComponent(jLabel22)))
                                                .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(txtmenorrombo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(2, 2, 2))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtladorombo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtmayorrombo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addComponent(Btnarearombo)
                                        .addComponent(Btnperimetrorombo))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(694, 694, 694)
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(jLabel1)
                            .addGap(150, 150, 150))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Btnperimetrorectangulo)
                                .addComponent(Btnarearectangulo)
                                .addComponent(Bntborrarrectangulo))
                            .addGap(25, 25, 25))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel35)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtperimetrotrapecio, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Btnareatrapecio, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel29)
                                        .addComponent(jLabel28)
                                        .addComponent(jLabel30))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtlado2trapecio, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtlado1trapecio, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtbasemayortrapecio, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(84, 84, 84))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtareatrapecio, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtbasemenortrapecio, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtalturatrapecio, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Btnborrartrapecio))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel27))
                            .addComponent(Btnperimetrotrapecio))
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel21))
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(24, 24, 24)))
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtbaserectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcuadradolado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(txtbasetriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtradiocirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(txtladorombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)
                            .addComponent(txtlado1trapecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtlado2trapecio)
                            .addComponent(jLabel29))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtalturarectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtarearectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtcuadradoperimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtcuadradoarea, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtperimetrorectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(BtnareaCuadrado))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(Btnarearectangulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btnperimetrorectangulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bntborrarrectangulo))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnperimetroCuadrado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnBorrarCuadrado))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtalturatriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13)
                                        .addComponent(txtareacirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel23)
                                        .addComponent(txtmayorrombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel30)
                                        .addComponent(txtbasemayortrapecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtareatriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel19)
                                            .addComponent(txtperimetrotriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtperimetrocirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel24)
                                            .addComponent(txtmenorrombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtbasemenortrapecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel20)
                                            .addComponent(txthipotenusatriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtalturatrapecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel33)
                                            .addComponent(txtareatrapecio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel35)
                                            .addComponent(txtperimetrotrapecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel32)))
                        .addGap(22, 22, 22)
                        .addComponent(Btnperimetrorombo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Btnareacirculo)
                                    .addComponent(jLabel25)
                                    .addComponent(txtarearombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Btnperimetrocirculo)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtperimetrorombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BtnBorrarCirculo)
                                    .addComponent(Btnarearombo)))
                            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btnborrartriangulo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Btnareatrapecio)
                        .addGap(3, 3, 3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btnborrararombo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Btnperimetrotrapecio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btnborrartrapecio)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    
    private void BtnareaCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnareaCuadradoActionPerformed
        // TODO add your handling code here:
        double areacuadrado;
        int lado;
        lado = Integer.parseInt(txtcuadradolado.getText());
        Cuadrado figura3 = new Cuadrado(lado);
        areacuadrado = figura3.calcularArea();
        txtcuadradoarea.setText(String.valueOf(areacuadrado));
    }//GEN-LAST:event_BtnareaCuadradoActionPerformed

    
    private void BtnperimetroCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnperimetroCuadradoActionPerformed
        // TODO add your handling code here:
        double perimetrocuadrado;
        int lado;
        lado = Integer.parseInt(txtcuadradolado.getText());
        Cuadrado figura3 = new Cuadrado(lado);
         perimetrocuadrado= figura3.calcularPerimetro();
        txtcuadradoperimetro.setText(String.valueOf( perimetrocuadrado));
    }//GEN-LAST:event_BtnperimetroCuadradoActionPerformed

    private void BtnBorrarCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarCuadradoActionPerformed
        // TODO add your handling code here:
        txtcuadradolado.setText("");
        txtcuadradoarea.setText("");
        txtcuadradoperimetro.setText("");
    }//GEN-LAST:event_BtnBorrarCuadradoActionPerformed

    private void txtcuadradoperimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcuadradoperimetroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcuadradoperimetroActionPerformed

    private void txtcuadradoareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcuadradoareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcuadradoareaActionPerformed

    private void BtnarearectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnarearectanguloActionPerformed
        // TODO add your handling code here:
        int base, altura;
        double arearectangulo;
        base = Integer.parseInt(txtbaserectangulo.getText());
        altura = Integer.parseInt(txtalturarectangulo.getText());
        Rectangulo figura2 = new Rectangulo(base,altura);
        arearectangulo = figura2.calcularArea();
        txtarearectangulo.setText(String.valueOf(arearectangulo)); 
    }//GEN-LAST:event_BtnarearectanguloActionPerformed

    private void BtnperimetrorectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnperimetrorectanguloActionPerformed
        // TODO add your handling code here:
        int base, altura;
        double perimetrorectangulo;
        base = Integer.parseInt(txtbaserectangulo.getText());
        altura = Integer.parseInt(txtalturarectangulo.getText());
        Rectangulo figura2 = new Rectangulo(base,altura);
        perimetrorectangulo = figura2.calcularPerimetro();
        txtperimetrorectangulo.setText(String.valueOf(perimetrorectangulo));
    }//GEN-LAST:event_BtnperimetrorectanguloActionPerformed

    private void BntborrarrectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntborrarrectanguloActionPerformed
        // TODO add your handling code here:
    txtbaserectangulo.setText("");
    txtalturarectangulo.setText("");
    txtarearectangulo.setText("");
    txtperimetrorectangulo.setText("");
    }//GEN-LAST:event_BntborrarrectanguloActionPerformed

    private void txtperimetrocirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtperimetrocirculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtperimetrocirculoActionPerformed

    private void BtnareacirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnareacirculoActionPerformed
        // TODO add your handling code here:
        double area;
        int Radio;
        Radio = Integer.parseInt(txtradiocirculo.getText());
        Circulo figura1 = new Circulo(Radio);
        area=figura1.calcularArea();
        txtareacirculo.setText(String.valueOf(area));
    }//GEN-LAST:event_BtnareacirculoActionPerformed

    private void BtnperimetrocirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnperimetrocirculoActionPerformed
        // TODO add your handling code here:
        double perimetrocirculo;
        int Radio;
        Radio = Integer.parseInt(txtradiocirculo.getText());
        Circulo figura1 = new Circulo(Radio);
        perimetrocirculo=figura1.calcularPerimetro();
        txtperimetrocirculo.setText(String.valueOf(perimetrocirculo));
    }//GEN-LAST:event_BtnperimetrocirculoActionPerformed

    private void BtnBorrarCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarCirculoActionPerformed
        // TODO add your handling code here:
        txtradiocirculo.setText("");
        txtareacirculo.setText("");
        txtperimetrocirculo.setText("");
    }//GEN-LAST:event_BtnBorrarCirculoActionPerformed

    private void txtbasetrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbasetrianguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbasetrianguloActionPerformed

    private void BtnareatrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnareatrianguloActionPerformed
        // TODO add your handling code here:
        int Base, Altura;
        double areaTriangulo;
        Base = Integer.parseInt(txtbasetriangulo.getText());
        Altura = Integer.parseInt(txtalturatriangulo.getText());
        Triangulo figura4 = new Triangulo(Base,Altura);
        areaTriangulo= figura4.calcularArea();
        txtareatriangulo.setText(String.valueOf(areaTriangulo));
    }//GEN-LAST:event_BtnareatrianguloActionPerformed

    private void BtnperimetrotrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnperimetrotrianguloActionPerformed
        // TODO add your handling code here:
        int Base, Altura;
        double perimetroTriangulo;
        Base = Integer.parseInt(txtbasetriangulo.getText());
        Altura = Integer.parseInt(txtalturatriangulo.getText());
        Triangulo figura4 = new Triangulo(Base,Altura);
        perimetroTriangulo = figura4.calcularPerimetro();
        txtperimetrotriangulo.setText(String.valueOf(perimetroTriangulo));
    }//GEN-LAST:event_BtnperimetrotrianguloActionPerformed

    private void BtnhipotenusatrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnhipotenusatrianguloActionPerformed
        // TODO add your handling code here:
                int Base, Altura;
        double hipotenusaTriangulo;
        Base = Integer.parseInt(txtbasetriangulo.getText());
        Altura = Integer.parseInt(txtalturatriangulo.getText());
        Triangulo figura4 = new Triangulo(Base,Altura);
        hipotenusaTriangulo = figura4.calcularHipotenusa();
        txthipotenusatriangulo.setText(String.valueOf(hipotenusaTriangulo));
    }//GEN-LAST:event_BtnhipotenusatrianguloActionPerformed

    private void BtnborrartrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnborrartrianguloActionPerformed
        // TODO add your handling code here:
    txtbasetriangulo.setText("");
    txtalturatriangulo.setText("");
    txtareatriangulo.setText("");
    txtperimetrotriangulo.setText("");
    txthipotenusatriangulo.setText("");
    }//GEN-LAST:event_BtnborrartrianguloActionPerformed

    private void txtladoromboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtladoromboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtladoromboActionPerformed

    private void BtnperimetroromboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnperimetroromboActionPerformed
        // TODO add your handling code here:
        double lado, diagonalMenor, diagonalMayor, perimetrorombo;
        lado = Integer.parseInt(txtladorombo.getText());
        diagonalMenor = Integer.parseInt(txtmenorrombo.getText());
        diagonalMayor = Integer.parseInt(txtmayorrombo.getText());
        Rombo figura5 = new Rombo(lado,diagonalMenor,diagonalMayor);
        perimetrorombo = figura5.calcularPerimetro();
        txtperimetrorombo.setText(String.valueOf(perimetrorombo));
    }//GEN-LAST:event_BtnperimetroromboActionPerformed

    private void txtperimetroromboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtperimetroromboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtperimetroromboActionPerformed

    private void BtnarearomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnarearomboActionPerformed
        // TODO add your handling code here:
        double lado, diagonalMenor, diagonalMayor, arearombo;
        lado = Integer.parseInt(txtladorombo.getText());
        diagonalMenor = Integer.parseInt(txtmenorrombo.getText());
        diagonalMayor = Integer.parseInt(txtmayorrombo.getText());
        Rombo figura5 = new Rombo(lado,diagonalMenor,diagonalMayor);
        arearombo = figura5.calcularArea();
        txtarearombo.setText(String.valueOf(arearombo));
 
    }//GEN-LAST:event_BtnarearomboActionPerformed

    private void BtnborrararomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnborrararomboActionPerformed
        // TODO add your handling code here:
        txtladorombo.setText("");
        txtmenorrombo.setText("");
        txtmayorrombo.setText("");
        txtarearombo.setText("");
        txtperimetrorombo.setText("");
    }//GEN-LAST:event_BtnborrararomboActionPerformed

    private void BtnareatrapecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnareatrapecioActionPerformed
        // TODO add your handling code here:
        double lado1, lado2, baseMenor;
        double baseMayor, Altura, areatrapecio;
        lado1 = Integer.parseInt(txtlado1trapecio.getText());
        lado2 = Integer.parseInt(txtlado2trapecio.getText());
        Altura = Integer.parseInt(txtalturatrapecio.getText());
        baseMenor = Integer.parseInt(txtbasemenortrapecio.getText());
        baseMayor = Integer.parseInt(txtbasemayortrapecio.getText());
        Trapecio figura6 = new Trapecio(lado1,lado2,baseMenor,baseMayor,Altura);
        areatrapecio = figura6.calcularArea();
        txtareatrapecio.setText(String.valueOf(areatrapecio));
    }//GEN-LAST:event_BtnareatrapecioActionPerformed

    private void BtnperimetrotrapecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnperimetrotrapecioActionPerformed
        // TODO add your handling code here:
        double lado1, lado2, baseMenor;
        double baseMayor, Altura, perimetrotrapecio;
        lado1 = Integer.parseInt(txtlado1trapecio.getText());
        lado2 = Integer.parseInt(txtlado2trapecio.getText());
        Altura = Integer.parseInt(txtalturatrapecio.getText());
        baseMenor = Integer.parseInt(txtbasemenortrapecio.getText());
        baseMayor = Integer.parseInt(txtbasemayortrapecio.getText());
        Trapecio figura6 = new Trapecio(lado1,lado2,baseMenor,baseMayor,Altura);
        perimetrotrapecio = figura6.calcularPerimetro();
        txtperimetrotrapecio.setText(String.valueOf(perimetrotrapecio));
    }//GEN-LAST:event_BtnperimetrotrapecioActionPerformed

    private void BtnborrartrapecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnborrartrapecioActionPerformed
        // TODO add your handling code here:
        txtlado1trapecio.setText("");
        txtlado2trapecio.setText("");
        txtalturatrapecio.setText("");
        txtbasemayortrapecio.setText("");
        txtbasemenortrapecio.setText("");
        txtareatrapecio.setText("");
        txtperimetrotrapecio.setText("");
    }//GEN-LAST:event_BtnborrartrapecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bntborrarrectangulo;
    private javax.swing.JButton BtnBorrarCirculo;
    private javax.swing.JButton BtnBorrarCuadrado;
    private javax.swing.JButton BtnareaCuadrado;
    private javax.swing.JButton Btnareacirculo;
    private javax.swing.JButton Btnarearectangulo;
    private javax.swing.JButton Btnarearombo;
    private javax.swing.JButton Btnareatrapecio;
    private javax.swing.JButton Btnareatriangulo;
    private javax.swing.JButton Btnborrararombo;
    private javax.swing.JButton Btnborrartrapecio;
    private javax.swing.JButton Btnborrartriangulo;
    private javax.swing.JButton Btnhipotenusatriangulo;
    private javax.swing.JButton BtnperimetroCuadrado;
    private javax.swing.JButton Btnperimetrocirculo;
    private javax.swing.JButton Btnperimetrorectangulo;
    private javax.swing.JButton Btnperimetrorombo;
    private javax.swing.JButton Btnperimetrotrapecio;
    private javax.swing.JButton Btnperimetrotriangulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField txtalturarectangulo;
    private javax.swing.JTextField txtalturatrapecio;
    private javax.swing.JTextField txtalturatriangulo;
    private javax.swing.JTextField txtareacirculo;
    private javax.swing.JTextField txtarearectangulo;
    private javax.swing.JTextField txtarearombo;
    private javax.swing.JTextField txtareatrapecio;
    private javax.swing.JTextField txtareatriangulo;
    private javax.swing.JTextField txtbasemayortrapecio;
    private javax.swing.JTextField txtbasemenortrapecio;
    private javax.swing.JTextField txtbaserectangulo;
    private javax.swing.JTextField txtbasetriangulo;
    private javax.swing.JTextField txtcuadradoarea;
    private javax.swing.JTextField txtcuadradolado;
    private javax.swing.JTextField txtcuadradoperimetro;
    private javax.swing.JTextField txthipotenusatriangulo;
    private javax.swing.JTextField txtlado1trapecio;
    private javax.swing.JTextField txtlado2trapecio;
    private javax.swing.JTextField txtladorombo;
    private javax.swing.JTextField txtmayorrombo;
    private javax.swing.JTextField txtmenorrombo;
    private javax.swing.JTextField txtperimetrocirculo;
    private javax.swing.JTextField txtperimetrorectangulo;
    private javax.swing.JTextField txtperimetrorombo;
    private javax.swing.JTextField txtperimetrotrapecio;
    private javax.swing.JTextField txtperimetrotriangulo;
    private javax.swing.JTextField txtradiocirculo;
    // End of variables declaration//GEN-END:variables
}
